[lib]
crate-type = ["cdylib", "lib"]

[package]
name = "cif_chomper_core"
version = "0.1.0"
license = "LGPL-3.0"
edition = "2024"
description = "Core tools for generating data structures for DDL dictionaries such as the CIF format."
repository = "https://github.com/d-perl/cif_chomper"
categories = ["science"]
keywords = ["CIF", "crystallography", "parser"]

[dependencies]
log = "0.4.29"
const-str = "0.6.4"
nom = "8.0.0"
proc-macro2 = "1.0.106"
quote = "1.0.45"
syn.workspace = true
phf_codegen = "0.13.1"

[dev-dependencies]
rstest = "0.25.0"
